package org.iaeste.szakal2.models.entities;

public enum ContactStatus {
    ASSIGNED, CALL_LATER, NOT_INTERESTED, INTERNSHIP, WAITING_FOR_RESPONSE, BARTER, SPONSOR, TRAINING, DIFFERENT_FORM_PARTNERSHIP,
    CALL_NEXT_YEAR, I_HAVE_TO_CONTACT_COMPANY, COMPANY_WILL_REACH_OUT
}
