package org.iaeste.szakal2.models.entities;

public enum ContactStatus {
    ASSIGNED, CALL_LATER, NOT_INTERESTED, INTERNSHIP, WAITING_FOR_RESPONSE, BARTER, SPONSOR, TRAINING, DIFFERENT_FORM_PARTNERSHIP
}
