name: Heroku deploy

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging"
        required: false
        default: false
      release_level:
        type: choice
        description: "Level of deployment"
        options:
          - major
          - minor
          - patch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      EMAIL: ${{secrets.EMAIL}} 
      PASSWORD: ${{secrets.PASSWORD}}  
      HEROKU_API_TOKEN: ${{secrets.HEROKU_API_TOKEN}}  
      LAST_COMMIT_MESSAGE: ${{github.event.commits[0].message}}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12

      - name: Run semver
        working-directory: ./
        run: ./gradlew createSemverTag "-Psemver.stage=final" "-Psemver.scope=${{inputs.release_level}}" && ./gradlew updateVersionInFiles

      - name: Run integration test
        working-directory: ./
        run: ./gradlew :backend:integrationTest

      - name: Set up env
        working-directory: ./
        run: sudo bash ./setup-env-docker.sh

      - name: Install node modules
        working-directory: ./frontend
        run: npm install

      - name: Install psql
        working-directory: ./
        run: sudo apt install postgresql-client-common && sudo apt install postgresql-client-14

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Run cypress tests
        working-directory: ./frontend
        run: CYPRESS_CACHE_FOLDER=./tmp/Cypress sudo npx cypress install --force && DEBUG=cypress:* sudo npx cypress run --browser chrome

      - name: Build frontend
        working-directory: ./
        run: sudo bash ./build-and-copy.sh true

      - name: Heroku upload
        run: |  
          export JAVA_HOME=JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.1-12/x64
          sudo chmod +x "${GITHUB_WORKSPACE}/cicd/deploy.sh"
          sudo "${GITHUB_WORKSPACE}/cicd/deploy.sh" ${HEROKU_API_TOKEN} ${LAST_COMMIT_MESSAGE} false
        shell: bash

      - name: Push new tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: false
          tags: true
